# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    install -g @angular/cli
    npm install
    npm install express
    npm run build
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Azure Internal Consumption(1)(fbb69af7-f9a0-4e69-ba10-b4eb445e3963)'
    appType: 'webAppLinux'
    WebAppName: 'nginxrepo'
    packageForLinux: 'dist/'
    RuntimeStack: 'NODE|lts'
    ScriptType: 'Inline Script'
    InlineScript: ':: You can provide your deployment commands here. One command per line.'